cargo-features = ["edition2024", "codegen-backend"]


[profile.dev]
codegen-backend = "cranelift"
panic = 'abort'


[package]
name = "pipedream"
version = "0.3.0"
edition = "2024"


[workspace]
members = [
    "bichannel",
    "engine",
    "interface",
    "prefab",
]


[workspace.dependencies]
crossbeam = "0.8.1"
rand = "0.8.5"
strum = "0.26.2"
strum_macros = "0.26.4"

log = { version = "0.4.21", features = ["kv"] }
log4rs = "1.3.0"
tui-logger = "0.11.1"

quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }
proc-macro2 = "1.0.86"

serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.122"

rusqlite = { version = "0.31.0", features = ["serde_json", "bundled", "trace"] }
serde_rusqlite = "0.35.0"

image = "0.25.2"

crossterm = "0.27.0"
ratatui = { version = "0.26.3", features = ["all-widgets"] }
tui-markup = { version = "0.4.0", features = ["ratatui"] }


[dependencies]
bichannel = { path = "bichannel" }
rusqlite_orm = { path = "rusqlite_orm" }
pipedream_engine = { path = "engine" }
pipedream_domain = { path = "domain" }
pipedream_interface = { path = "interface" }
pipedream_prefab = { path = "prefab" }
