cargo-features = ["edition2024", "codegen-backend"]


[profile.dev]
codegen-backend = "cranelift"
panic = 'abort'


[package]
name = "pipedream"
version = "0.3.0"
edition = "2024"


[workspace]
members = [
    "bichannel",
    "engine",
    "interface",
    "prefab",
]


[dependencies]
pipedream-bichannel = { path = "bichannel" }
pipedream-engine = { path = "engine" }
pipedream-interface = { path = "interface" }
pipedream-prefab = { path = "prefab" }
