cargo-features = ["edition2024"]

[package]
name = "pipedream"
version = "0.1.0"
edition = "2024"

[dependencies]
bichannel = "0.0.4"
crossterm = "0.27.0"
ratatui = { version = "0.26.2", features = ["all-widgets"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_yaml = "0.9.34"
