cargo-features = ["edition2024", "codegen-backend"]


[package]
name = "pipedream-interface"
version = "0.3.0"
edition = "2024"


[dependencies]
pipedream-engine = { path = "../engine" }

fixed = { version = "1.27.0", features = ["serde", "serde-str"]}
bichannel = "0.0.4"

log = { version = "0.4.21", features = ["kv"] }
tui-logger = "0.11.1"
log4rs = "1.3.0"

crossterm = "0.27.0"
ratatui = { version = "0.26.3", features = ["all-widgets"] }
tui-markup = { version = "0.4.0", features = ["ratatui"] }

image = "0.25.1"

strum = "0.26.2"
strum_macros = "0.26.4"
